// flow-typed signature: 3f39a310d21fce0d2cd399c82112d6b6
// flow-typed version: <<STUB>>/cssjanus_v^1.3.0/flow_v0.132.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'cssjanus'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'cssjanus' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'cssjanus/src/cssjanus' {
  declare module.exports: any;
}

// Filename aliases
declare module 'cssjanus/src/cssjanus.js' {
  declare module.exports: $Exports<'cssjanus/src/cssjanus'>;
}
