// flow-typed signature: 188df1cf4066e2436bcd157f72408cb7
// flow-typed version: <<STUB>>/stylis_v3.x/flow_v0.132.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'stylis'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'stylis' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'stylis/src/Enum' {
  declare module.exports: any;
}

declare module 'stylis/src/Middleware' {
  declare module.exports: any;
}

declare module 'stylis/src/Parser' {
  declare module.exports: any;
}

declare module 'stylis/src/Prefixer' {
  declare module.exports: any;
}

declare module 'stylis/src/Serializer' {
  declare module.exports: any;
}

declare module 'stylis/src/Tokenizer' {
  declare module.exports: any;
}

declare module 'stylis/src/Utility' {
  declare module.exports: any;
}

// Filename aliases
declare module 'stylis/index' {
  declare module.exports: $Exports<'stylis'>;
}
declare module 'stylis/index.js' {
  declare module.exports: $Exports<'stylis'>;
}
declare module 'stylis/src/Enum.js' {
  declare module.exports: $Exports<'stylis/src/Enum'>;
}
declare module 'stylis/src/Middleware.js' {
  declare module.exports: $Exports<'stylis/src/Middleware'>;
}
declare module 'stylis/src/Parser.js' {
  declare module.exports: $Exports<'stylis/src/Parser'>;
}
declare module 'stylis/src/Prefixer.js' {
  declare module.exports: $Exports<'stylis/src/Prefixer'>;
}
declare module 'stylis/src/Serializer.js' {
  declare module.exports: $Exports<'stylis/src/Serializer'>;
}
declare module 'stylis/src/Tokenizer.js' {
  declare module.exports: $Exports<'stylis/src/Tokenizer'>;
}
declare module 'stylis/src/Utility.js' {
  declare module.exports: $Exports<'stylis/src/Utility'>;
}
